apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
stringData:
  postgres-host: postgres-order-service
  postgres-port: "5432"
  postgres-user-database: users-database
  postgres-order-database: orders-database
  postgres-username: user
  postgres-password: "12345"
  postgres-connection-string: "Host=postgres-order-service;Port=5432;Database=orders-database;Username=user;Password=12345"
  postgres-user-connection-string: "Host=postgres-user-service;Port=5432;Database=users-database;Username=user;Password=12345"