GET http://localhost:5215/headers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjAxOWExNzQwLWExYjUtNzk5NC1iOWY4LTJhNzI1OWVjMWQzYSIsImp0aSI6IjA4NzZjYTUxLTU4YjEtNGJmNS1iNzBjLTNkZjBmMDQwYmFhZiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6ItCf0L7Qu9GM0LfQvtCy0LDRgtC10LvRjCIsInJvbGVfaWQiOiIxYjAxY2VkYS1lNTI0LTRhZDItYTdlZi0yZDA4MTg5NGQ2YTgiLCJleHAiOjE3NjE0NzEzMTQsImlzcyI6Ik15RGVmZWN0TWFuYWdtZW50U2VydmVyIiwiYXVkIjoiTXlEZWZlY3RNYW5hZ21lbnRBdWRpZW5jZSJ9.sP2Nl0T-SwF5bYREhMJ0Uu3azjOH6kq--5naLxZqRV4